#!/usr/bin/ruby
require "httparty"

# Argument Parsing
args = Hash[ ARGV.join(' ').scan(/--?([^=\s]+)(?:=(\S+))?/) ]
symbol = args["s"]
currency = args["c"]
data = args["d"]


# Request
host = "https://api.coinbase.com/v2/prices/#{symbol}-#{currency}/spot"
response = HTTParty.get(host)
parsed_response = response.dig('data', 'amount')


text = "\033[32mPrice(#{symbol.upcase} to #{currency.upcase}): \033[1;37m#{parsed_response} "

# Print it
puts("""\033[33m     
──▄▄█▀▀▀▀▀█▄▄──
▄█▀░░▄░▄░░░░▀█▄     
█░░░▀█▀▀▀▀▄░░░█     
█░░░░█▄▄▄▄▀░░░█   #{text}\033[33m
█░░░░█░░░░█░░░█
▀█▄░▀▀█▀█▀░░▄█▀
──▀▀█▄▄▄▄▄█▀▀──
    """)
